name: continuous integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Fix Conda permissions on macOS
      run: sudo chown -R $UID $CONDA
      if: matrix.os == 'macos-latest'
    - name: Install conda dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Install package
      run: |
        pip install .[tests]
    - name: yapf check
      run: |
        yapf -r --diff molscore tests
    - name: type checking
      run: |
        mypy molscore
    - name: Test with pytest and coverage
      run: |
        conda install pytest coverage
        coverage run --source="molscore" --omit="molscore" -m pytest tests
    - name: Get coverage report
      run: |
        coverage report
    - name: Coveralls
      uses: codecov/codecov-action@v1
